name: Publish package to the Maven Central Repository
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Run tests
        run: ./gradlew test
  publish:
    name: Publish artifact
    runs-on: ubuntu-latest
    if: contains(fromJSON('["main", "develop"]'), github.ref_name)
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Publish snapshot package
        if: github.ref_name == 'develop'
        run: |
          ./gradlew publish \
          -PmavenUsername=${{ secrets.MAVEN_REPOSITORY_USERNAME }} \
          -PmavenPassword='${{ secrets.MAVEN_REPOSITORY_PASSWORD }}' \
          -PsigningKey=${{ secrets.SIGNING_SECRET_KEY }} \
          -PsigningPassword=${{ secrets.SIGNING_PASSPHRASE }} \
          -Psnapshot
      - name: Publish release package
        if: github.ref_name == 'main'
        run: |
          ./gradlew publish \
          -PmavenUsername=${{ secrets.MAVEN_REPOSITORY_USERNAME }} \
          -PmavenPassword='${{ secrets.MAVEN_REPOSITORY_PASSWORD }}' \
          -PsigningKey=${{ secrets.SIGNING_SECRET_KEY }} \
          -PsigningPassword=${{ secrets.SIGNING_PASSPHRASE }}
      - name: Get version
        if: github.ref_name == 'main'
        run: echo "package_version=`./gradlew -q getVersion`" >> "$GITHUB_ENV"
      - name: Tag repository
        if: github.ref_name == 'main'
        run: git tag v${{ env.package_version }}
      - name: Push tag
        if: github.ref_name == 'main'
        run: git push --tags