name: Publish package to the Maven Central Repository
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Run tests
        run: ./gradlew test
  publish:
    name: Publish artifact
    runs-on: ubuntu-latest
    if: contains(fromJSON('["main", "develop"]'), github.ref_name)
    needs: test
    env:
      ORG_GRADLE_PROJECT_mavenUsername: ${{ secrets.MAVEN_REPOSITORY_USERNAME }}
      ORG_GRADLE_PROJECT_mavenPassword: ${{ secrets.MAVEN_REPOSITORY_PASSWORD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_SECRET_KEY }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSPHRASE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Publish snapshot package
        if: github.ref_name == 'develop'
        run: ./gradlew publish -Psnapshot
      - name: Publish release package
        if: github.ref_name == 'main'
        run: ./gradlew publish
      - name: Get version
        if: github.ref_name == 'main'
        run: echo "package_version=`./gradlew -q getVersion`" >> "$GITHUB_ENV"
      - name: Tag repository
        if: github.ref_name == 'main'
        run: git tag v${{ env.package_version }}
      - name: Push tag
        if: github.ref_name == 'main'
        run: git push --tags